### ISSUE TITLE
Newest version not published on npm ?

### ISSUE THREAD

**Issue by bortexz** [unclecheese/react-selectable#15]
Hi,

I have been trying to use selectOnMouseMove, but it doesn't appear to have been published in the version in npm. Navigating through the _openSelector code, this line is missing at the end:

```
if (this.props.selectOnMouseMove) this._throttledSelect();
```

I am working on a File Manager application for desktop, this module saved my day! 👍

**Comment by unclecheese** [comment]
Glad to hear it! I've bumped the version on npm. Sorry about that!
