### ISSUE TITLE
Pass event object to onSelection

### ISSUE THREAD

**Issue by Lukavyi** [unclecheese/react-selectable#21]
If you pass and event object to onSelection, it would be easier to capture ctrl, or cmd button press, in order to concat results.

**Comment by unclecheese** [comment]
True. If you submit a PR for that, I'd be happy to merge it.

**Comment by Lukavyi** [comment]
Thanks

**Comment by bortexz** [comment]
Hi, when selectOnMouseMove, the event is not passed. I open a PR for that
