### ISSUE TITLE
wrong calculations when fixedPosition=true

### ISSUE THREAD

**Issue by zivni** [unclecheese/react-selectable#52]
After commit bb9c4506f8b0b234e5f5e95a1c042a3efb52fdf3 (Fix positioning of drag box) the use of fixed position is wrong.

I think that this small change is fixing the problem: 
```
// selectable-group.js
_getInitialCoordinates() {
	if (this.props.fixedPosition) {
		return { x: 0, y: 0 }
	}
	//... rest of code ...
}
```

This reverses the effects of the change when using  fixedPosition=true

I tested this code and it seems to work O.k

BTW it may also fix the problem in #30

**Comment by bergice** [comment]
https://github.com/unclecheese/react-selectable/pull/57 should resolve this.

**Comment by unclecheese** [comment]
Closing as https://github.com/unclecheese/react-selectable/pull/57 has been merged.
