### ISSUE TITLE
react-selectable not working correctly inside absolutely positioned element

### ISSUE THREAD

**Issue by leopoldjoy** [unclecheese/react-selectable#9]
Hello,

When I place my `<SelectableGroup>` inside of another element that is `position: absolute`, the drag box is offset by a few hundred pixels and doesn't work. To show the problem, I used the demo and only changed `.main` to have the attribute `position: absolute`. Here's an example of the problem: https://jsfiddle.net/tcLyb278/

Why is the dragging offset so much? What can we do to fix this?

Thanks!

**Comment by unclecheese** [comment]
Use the `fixedPosition` prop. https://github.com/unclecheese/react-selectable/blob/master/src/selectable-group.js#L225

Needs to be documented.

**Comment by leopoldjoy** [comment]
Thanks unclecheese! I added documentation for `fixedPosition` and submitted a pull request.
